# fly.toml app configuration file generated for medusurf-dev-elpy on 2024-10-03T17:09:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medusurf-dev-elpy'
primary_region = 'sea'

[build]
  dockerfile = './Dockerfile'
  ignorefile = './.dockerignore'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 1250
    soft_limit = 1000

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
